---
-  hosts: all
   user: root
   become: yes
   connection: ssh
   tasks:
     - name: installing git
       yum:
         name: git
         state: present
     - debug:
         msg: "port num for the environement {{env}} is {{portnum}}"
